import { z } from "zod";

export const storyScriptSchema = z.object({
  style_anchor: z
    .string()
    .min(10)
    .describe(
      "One-sentence style/atmosphere prefix that every frame image inherits so the 5 keyframes stay visually consistent (same character, lighting, palette, film stock)."
    ),
  frames: z
    .array(
      z.object({
        index: z.number().int().min(1).max(5),
        description: z.string().min(5),
        camera: z.string().min(2),
        mood: z.string().min(2),
      })
    )
    .length(5),
  scenes: z
    .array(
      z.object({
        index: z.number().int().min(1).max(4),
        prompt: z.string().min(10),
        motion: z.string().min(2),
      })
    )
    .length(4),
});

export type StoryScript = z.infer<typeof storyScriptSchema>;

export const STORY_SCRIPT_SYSTEM_PROMPT = `You are a cinematic storyboard writer for short vertical ad videos.

Your output is a 5-keyframe / 4-scene storyboard:
- Frame 1 is the first image of clip 1.
- Frame 2 is the LAST frame of clip 1 AND the FIRST frame of clip 2.
- Frame 3 is the LAST frame of clip 2 AND the FIRST frame of clip 3.
- Frame 4 is the LAST frame of clip 3 AND the FIRST frame of clip 4.
- Frame 5 is the LAST frame of clip 4.

Each scene/clip is generated by Veo 3.1 with both its first and last frame fixed —
you are writing the motion/action that happens BETWEEN the two keyframes.

Rules:
1. Visual continuity is everything. Frame N must end where frame N+1 begins — same subject, same location, same lighting. The scene prompt describes how the camera / subject moves from N to N+1.
2. Keep the protagonist, palette, and film stock identical across all 5 frames. Put those invariants in \`style_anchor\` so they auto-apply to every Imagen call.
3. Frame descriptions should be concrete: subject, action pose, environment, lighting, camera angle. No abstract adjectives alone.
4. Scene prompts focus on MOTION between frame N and N+1 — camera move, character action, lighting shift, prop animation. Do not re-describe the keyframes themselves.
5. 4 scenes total form ONE coherent narrative (beginning → development → turn → payoff).

Respond with valid JSON only — no markdown, no prose.`;

export function buildStoryScriptUserPrompt(input: {
  topic: string;
  aspectRatio: "9:16" | "16:9" | "1:1";
  durationPerClip: number;
}): string {
  return `Story topic: ${input.topic}
Output aspect ratio: ${input.aspectRatio}
Each clip duration: ${input.durationPerClip} seconds (total video: ${input.durationPerClip * 4}s)

Produce exactly 5 frames and 4 scenes following the schema. Remember:
- frames[i].description = the still image at keyframe i
- scenes[i].prompt = the motion/action between frame i and frame i+1
- style_anchor = the sentence prefix applied to every frame for visual consistency`;
}
